/**
 * Mapping of equipment to associated muscles (including primary target and secondary muscles).
 * Used to provide context-aware muscle selection at L2 based on L1 equipment choices.
 */

export const EQUIPMENT_MUSCLES_MAP: Record<string, string[]> = {
  treadmill: [
    'cardiovascular system',
    'feet',
    'calves',
    'quadriceps',
    'hamstrings',
    'glutes',
    'ankles',
    'shins',
    'core',
  ],
  'stepmill machine': [
    'cardiovascular system',
    'feet',
    'calves',
    'quadriceps',
    'hamstrings',
    'glutes',
    'ankles',
    'shins',
    'core',
  ],
  'stationary bike': [
    'cardiovascular system',
    'quadriceps',
    'hamstrings',
    'calves',
    'glutes',
    'feet',
    'ankles',
    'hip flexors',
  ],
  'elliptical machine': [
    'cardiovascular system',
    'quadriceps',
    'hamstrings',
    'glutes',
    'calves',
    'feet',
    'shoulders',
    'core',
  ],
  'skierg machine': [
    'cardiovascular system',
    'lats',
    'shoulders',
    'triceps',
    'core',
    'upper back',
    'lower back',
  ],
  'upper body ergometer': [
    'cardiovascular system',
    'shoulders',
    'biceps',
    'triceps',
    'forearms',
    'chest',
    'upper back',
  ],
  rope: [
    'cardiovascular system',
    'calves',
    'quadriceps',
    'hamstrings',
    'glutes',
    'shoulders',
    'forearms',
    'feet',
    'ankles',
    'wrists',
  ],
  dumbbell: [
    'biceps',
    'triceps',
    'chest',
    'pectorals',
    'delts',
    'shoulders',
    'upper back',
    'lower back',
    'lats',
    'traps',
    'quadriceps',
    'hamstrings',
    'glutes',
    'calves',
    'forearms',
    'abs',
    'obliques',
    'core',
  ],
  barbell: [
    'chest',
    'pectorals',
    'biceps',
    'triceps',
    'delts',
    'shoulders',
    'upper back',
    'lower back',
    'lats',
    'traps',
    'quadriceps',
    'hamstrings',
    'glutes',
    'calves',
    'forearms',
    'abs',
    'core',
  ],
  'olympic barbell': [
    'chest',
    'pectorals',
    'shoulders',
    'delts',
    'quadriceps',
    'hamstrings',
    'glutes',
    'upper back',
    'traps',
    'calves',
  ],
  'ez barbell': [
    'biceps',
    'triceps',
    'forearms',
    'chest',
    'shoulders',
    'wrists',
  ],
  'trap bar': [
    'quadriceps',
    'hamstrings',
    'glutes',
    'traps',
    'lower back',
    'calves',
    'forearms',
  ],
  cable: [
    'chest',
    'pectorals',
    'biceps',
    'triceps',
    'delts',
    'shoulders',
    'lats',
    'upper back',
    'lower back',
    'abs',
    'obliques',
    'core',
    'glutes',
    'adductors',
    'abductors',
  ],
  kettlebell: [
    'glutes',
    'hamstrings',
    'quadriceps',
    'shoulders',
    'delts',
    'core',
    'abs',
    'upper back',
    'forearms',
    'cardiovascular system',
  ],
  'body weight': [
    'abs',
    'obliques',
    'core',
    'chest',
    'pectorals',
    'triceps',
    'biceps',
    'delts',
    'shoulders',
    'quadriceps',
    'hamstrings',
    'glutes',
    'calves',
    'cardiovascular system',
    'lats',
    'lower back',
    'upper back',
    'feet',
    'ankles',
  ],
  'leverage machine': [
    'chest',
    'pectorals',
    'lats',
    'upper back',
    'delts',
    'shoulders',
    'biceps',
    'triceps',
    'quadriceps',
    'hamstrings',
    'calves',
    'glutes',
    'cardiovascular system',
  ],
  'smith machine': [
    'chest',
    'pectorals',
    'quadriceps',
    'hamstrings',
    'glutes',
    'calves',
    'shoulders',
    'delts',
    'traps',
  ],
  band: [
    'shoulders',
    'delts',
    'biceps',
    'triceps',
    'chest',
    'upper back',
    'lats',
    'glutes',
    'hamstrings',
    'quadriceps',
    'hip flexors',
    'abductors',
    'adductors',
  ],
  'resistance band': [
    'shoulders',
    'delts',
    'biceps',
    'triceps',
    'chest',
    'upper back',
    'lats',
    'glutes',
    'hamstrings',
    'quadriceps',
    'hip flexors',
    'abductors',
    'adductors',
  ],
  'bosu ball': [
    'core',
    'abs',
    'obliques',
    'ankles',
    'calves',
    'quadriceps',
    'glutes',
    'feet',
  ],
  'stability ball': [
    'core',
    'abs',
    'obliques',
    'lower back',
    'chest',
    'hamstrings',
    'glutes',
  ],
  'medicine ball': [
    'core',
    'abs',
    'obliques',
    'shoulders',
    'chest',
    'glutes',
    'quadriceps',
  ],
  'wheel roller': [
    'abs',
    'core',
    'lower back',
    'lats',
    'shoulders',
    'hip flexors',
  ],
  roller: [
    'quadriceps',
    'hamstrings',
    'calves',
    'lats',
    'upper back',
    'glutes',
    'lower back',
  ],
  assisted: [
    'lats',
    'upper back',
    'chest',
    'triceps',
    'biceps',
    'core',
  ],
  tire: [
    'glutes',
    'hamstrings',
    'quadriceps',
    'core',
    'shoulders',
    'cardiovascular system',
    'traps',
  ],
  'sled machine': [
    'quadriceps',
    'hamstrings',
    'calves',
    'glutes',
    'core',
    'cardiovascular system',
    'feet',
  ],
  hammer: [
    'forearms',
    'wrists',
    'grip muscles',
    'shoulders',
    'core',
  ],
  weighted: [
    'abs',
    'core',
    'chest',
    'quadriceps',
    'hamstrings',
    'glutes',
    'triceps',
    'biceps',
    'shoulders',
  ],
};

/**
 * Maps UI-friendly or alias equipment names to backend API equipment names.
 */
export const mapEquipmentToApi = (equipment: string): string => {
  const lower = equipment.toLowerCase().trim();
  if (lower === 'treadmill') return 'stepmill machine';
  return lower;
};

/**
 * Returns the relevant muscles for a set of selected equipments.
 * If no equipment is selected, returns empty array (or all muscles can be used).
 */
export const getMusclesForEquipments = (equipments: string[]): string[] => {
  if (!equipments || equipments.length === 0) return [];

  const muscleSet = new Set<string>();
  for (const eq of equipments) {
    const key = eq.toLowerCase().trim();
    const mapped = EQUIPMENT_MUSCLES_MAP[key] || [];
    mapped.forEach((m) => muscleSet.add(m.toLowerCase()));
  }

  return Array.from(muscleSet).sort((a, b) => a.localeCompare(b));
};
